#!/bin/bash

# A bash script that helps me create notes in zet section

today=$(date +"%Y-%m-%d")

# function to prompt the user for a filename
get_filename() {
	read -p "Enter a filename: " filename
	echo "$filename"
}

# function to create and open a file in the specified directory
open_file() {

	# Cd into the directory
	cd "$1" || exit
	# Create the file in the specified directory
	touch "$1/$filename.md"

	# Format the file with the note template
	cat <<EOF >"$1/$filename.md"
# TITLE

${today}

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
EOF

	# Open
	nvim . "$1/$filename.md"
}

# Prompt the user if no filename is provided
if [[ $# -eq 0 ]]; then
	filename=$(get_filename)
fi

# if more than one argument is given, print error message and stop script
if [[ $# -gt 1 ]]; then
	echo "Please provide only one filename separated by dashes, without .md extension."
	echo "Example: zet my-new-note"
	exit 1
fi

# set filename to the argument given to the script
if [[ $# -eq 1 ]]; then
	filename=$1
fi

open_file "$ZET"
